#!/bin/bash

DATA_FILE="data.txt"
DATA_FILE_LIST=`cat $DATA_FILE`

TIME=`date +%Y%m%d_%H%M`
DIR="emcal_jet_cdf"
TAG=$1
JOBS_PACK=$2

DATA_PREFIX="subdata_"

NR_FILES=`wc -l $DATA_FILE | awk '{print $1}'`

NR_JOBS=$(($NR_FILES/$JOBS_PACK + 1))

DIR_JOBS="${DIR}_${TAG}_${TIME}"

mkdir -p $DIR_JOBS

echo "NR_FILES : " $NR_FILES
echo "NR_JOBS : " $NR_JOBS
echo "RUN DIR : " $DIR_JOBS

split -a 6 -d -l $JOBS_PACK data.txt $DATA_PREFIX

PROGRAM='aliroot -l -b -q EmcalJetCDF.C\(\"test\",\"local\",\"data.txt\"\)'

JOB_FILES="EmcalJetCDF.C AddTaskEmcalJetCDF.C AliAnalysisTaskEmcalJetCDF.cxx AliAnalysisTaskEmcalJetCDF.h InputData.C AliAnalysisTaskEmcalJetCDF_cxx.d AliAnalysisTaskEmcalJetCDF_cxx.so"

compileC_aliroot AliAnalysisTaskEmcalJetCDF.cxx

for data in `ls -1 $DATA_PREFIX*`
{
  IDX=${data#"subdata_"}

  ## create job dir
  SUBJOB_DIR=$DIR_JOBS/job_$IDX

  mkdir -pv $SUBJOB_DIR

  ## create the torque scripts
  SCRIPT=$SUBJOB_DIR/qsub_job

  cat head >> ${SCRIPT}
  echo "${PROGRAM}" >> $SCRIPT
  cat tail >> ${SCRIPT}

  mv $data  $SUBJOB_DIR/data.txt

  for file in $JOB_FILES
  do
    cp -L $file $SUBJOB_DIR/
  done

}


