#!/bin/bash

DATA_FILE="data.txt"
DATA_FILE_LIST=`cat $DATA_FILE`

TIME=`date +%Y%m%d_%H%M`
DIR="emcal_jet_cdf"
TAG=$1
JOBS_PACK=$2
ARG3=${3:-0}

DATA_PREFIX="subdata_"

NR_FILES=`wc -l $DATA_FILE | awk '{print $1}'`

NR_JOBS=$(($NR_FILES/$JOBS_PACK + 1))

DIR_JOBS="${DIR}_${TAG}_${TIME}"

mkdir -p $DIR_JOBS

echo "NR_FILES : " $NR_FILES
echo "NR_JOBS : " $NR_JOBS
echo "RUN DIR : " $DIR_JOBS


PROGRAM='root -b -l -q EmcalJetCDF.C\(\"local\",\"test\",\"data.txt\"\)'

JOB_FILES_LOCAL="EmcalJetCDF.C AddTaskEmcalJetSample.C AddTaskEmcalJetCDF.C AddTaskEmcalJetCDFUE.C AliAnalysisTaskEmcalJetCDF.cxx AliAnalysisTaskEmcalJetCDF.h AliAnalysisTaskEmcalJetCDFUE.cxx AliAnalysisTaskEmcalJetCDFUE.h InputData.C"

JOB_FILES_ALIROOT="EmcalJetCDF.C InputData.C"

JOB_FILES=$JOB_FILES_ALIROOT

if [[ "$ARG3" != "0" ]]
then
  JOB_FILES=$JOB_FILES_LOCAL
fi

echo $JOB_FILES


##split_data_files $DATA_FILE $NR_JOBS

split -a 6 -d -l $JOBS_PACK data.txt $DATA_PREFIX


for data in `ls -1 $DATA_PREFIX*`
{
  IDX=${data#"subdata_"}

  ## create job dir
  SUBJOB_DIR=$DIR_JOBS/job_$IDX

  mkdir -pv $SUBJOB_DIR

  ## create the torque scripts
  SCRIPT=$SUBJOB_DIR/qsub_job

  cat head >> ${SCRIPT}
  echo "${PROGRAM}" >> $SCRIPT
  cat tail >> ${SCRIPT}

  mv $data  $SUBJOB_DIR/data.txt

  for file in $JOB_FILES
  do
    cp $file $SUBJOB_DIR/
  done

}


